services:
  hugo:
    container_name: hugo
    image: "hugomods/hugo:dart-sass-go-git-0.147.5"
    ports:
      - 127.0.0.1:1313:1313
    volumes:
      - ${PWD}:/src
    working_dir: /src
    command:
      - server
      - --bind=0.0.0.0
      - --buildDrafts
      - --disableFastRender
      - --logLevel=debug
